[package]
name = "brainfuck"
version = "0.1.0"
authors = ["Federico Ravasio <ravasio.federico@gmail.com>"]

[lib]
name = "brainfuck"
path = "src/brainfuck/lib.rs"
bench = false
doctest = false

[[bin]]
name = "brainfuck"
bench = false
doc = false
test = false
